-- Instrucciones DML en Oracle
-- INSERT: Una sentencia INSERT de SQL agrega uno o más registros a una (y sólo una) tabla en una base de datos relacional.
-- UPDATE: Una sentencia UPDATE de SQL es utilizada para modificar los valores de un conjunto de registros existentes en una tabla.
-- MERGE: Lo que permite la sentencia SQL MERGE es, dependiendo de una condición lógica, actualizar registros (UPDATE) cuando la condición se cumple, o insertar registros(INSERT) cuando dicha condición no se cumple, de ahí surge la denominación de UPSERT.
-- DELETE: Una sentencia DELETE de SQL borra uno o más registros existentes en una tabla.
-- Instruccionesde Transferencia: Administran las modificaciones creadas por las instrucciones DML. Lo forman las instrucciones ROLLBACK, COMMIT y SAVEPOINT.