-- CREACION DE USUARIOS
CREATE USER C##SUCURSALES IDENTIFIED BY "123";

-- OTORGAR PRIVILEGIOS COMO DBA PARA QUE ADMINISTRE USUARIOS
GRANT DBA TO C##SUCURSALES;             

-- AQUI SE QUEDAN GUARDADO TODOS LOS USUARIOS QUE SE VAN CREANDO
SELECT * FROM DBA_USERS;


-- SI SE DESEA ELIMINAR EL USUARIO  (NO APLICA DELETE PORQUE ES UNA VISTA DE SOLO LECTURA Y NO UNA TABLA)
DROP USER C##SUCURSALES CASCADE;


-- REVOCAR LOS PERMISOS A UN DBA
REVOKE DBA FROM C##SUCURSALES;
-- CONSULTAR PRIVILEGIOS
SELECT * FROM DBA_SYS_PRIVS WHERE GRANTEE = 'C##SUCURSALES';


