-- CUALES SON: SELECT, INSERT, UPDATE, DELETE

INSERT ALL
    INTO categorias (id_categoria, nombre_categoria, desc_categoria) VALUES (1, 'TV', 'Televisores pequeños y portátiles')
    INTO categorias (id_categoria, nombre_categoria, desc_categoria) VALUES (2, 'Micro', 'Microondas compactos y eficientes')
    INTO categorias (id_categoria, nombre_categoria, desc_categoria) VALUES (3, 'Plancha', 'Planchas para ropa de tamaño portátil')
    INTO categorias (id_categoria, nombre_categoria, desc_categoria) VALUES (4, 'Radio', 'Radios AM/FM compactos y portátiles')
    INTO categorias (id_categoria, nombre_categoria, desc_categoria) VALUES (5, 'Tostador', 'Tostadoras para pan pequeñas y prácticas')
    INTO categorias (id_categoria, nombre_categoria, desc_categoria) VALUES (6, 'Licuadora', 'Licuadoras portátiles para jugos')
    INTO categorias (id_categoria, nombre_categoria, desc_categoria) VALUES (7, 'Exprimidor', 'Exprimidores de cítricos de mano')
    INTO categorias (id_categoria, nombre_categoria, desc_categoria) VALUES (8, 'Ventilador', 'Ventiladores personales y de mesa')
    INTO categorias (id_categoria, nombre_categoria, desc_categoria) VALUES (9, 'Cafetera', 'Cafeteras de 1 o 2 tazas')
    INTO categorias (id_categoria, nombre_categoria, desc_categoria) VALUES (10, 'Aspirador', 'Aspiradoras de mano para limpieza ligera')
    INTO categorias (id_categoria, nombre_categoria, desc_categoria) VALUES (11, 'Batidora', 'Batidoras de repostería pequeñas')
    INTO categorias (id_categoria, nombre_categoria, desc_categoria) VALUES (12, 'Secador', 'Secadores de cabello portátiles')
    INTO categorias (id_categoria, nombre_categoria, desc_categoria) VALUES (13, 'Calefactor', 'Calefactores eléctricos personales')
    INTO categorias (id_categoria, nombre_categoria, desc_categoria) VALUES (14, 'Freezer', 'Freezers pequeños para oficinas')
    INTO categorias (id_categoria, nombre_categoria, desc_categoria) VALUES (15, 'Sandwich', 'Sandwicheras portátiles y prácticas')
    INTO categorias (id_categoria, nombre_categoria, desc_categoria) VALUES (16, 'Reproductor', 'Reproductores multimedia portátiles')
    INTO categorias (id_categoria, nombre_categoria, desc_categoria) VALUES (17, 'Termo', 'Termos eléctricos para café o té')
    INTO categorias (id_categoria, nombre_categoria, desc_categoria) VALUES (18, 'Rizador', 'Rizadores de cabello de viaje')
    INTO categorias (id_categoria, nombre_categoria, desc_categoria) VALUES (19, 'Lámpara', 'Lámparas LED recargables')
    INTO categorias (id_categoria, nombre_categoria, desc_categoria) VALUES (20, 'Foco', 'Focos inteligentes pequeños')
    INTO categorias (id_categoria, nombre_categoria, desc_categoria) VALUES (21, 'Cortador', 'Cortadores de alimentos eléctricos')
    INTO categorias (id_categoria, nombre_categoria, desc_categoria) VALUES (22, 'Extractor', 'Extractores de jugos pequeños')
    INTO categorias (id_categoria, nombre_categoria, desc_categoria) VALUES (23, 'Calentador', 'Calentadores de agua de viaje')
    INTO categorias (id_categoria, nombre_categoria, desc_categoria) VALUES (24, 'Mezclador', 'Mezcladores de alimentos compactos')
    INTO categorias (id_categoria, nombre_categoria, desc_categoria) VALUES (25, 'Purificador', 'Purificadores de aire personales')
    INTO categorias (id_categoria, nombre_categoria, desc_categoria) VALUES (26, 'Enfriador', 'Enfriadores de aire compactos')
    INTO categorias (id_categoria, nombre_categoria, desc_categoria) VALUES (27, 'Procesador', 'Procesadores de alimentos pequeños')
    INTO categorias (id_categoria, nombre_categoria, desc_categoria) VALUES (28, 'Molino', 'Molinos de café portátiles')
    INTO categorias (id_categoria, nombre_categoria, desc_categoria) VALUES (29, 'Deshum', 'Deshumidificadores para habitaciones')
    INTO categorias (id_categoria, nombre_categoria, desc_categoria) VALUES (30, 'Estufa', 'Estufas eléctricas compactas')
    INTO categorias (id_categoria, nombre_categoria, desc_categoria) VALUES (31, 'Cortapelo', 'Cortapelos eléctricos recargables')
    INTO categorias (id_categoria, nombre_categoria, desc_categoria) VALUES (32, 'PlanchaV', 'Planchas verticales de vapor')
    INTO categorias (id_categoria, nombre_categoria, desc_categoria) VALUES (33, 'MiniBar', 'Mini refrigeradores para bebidas')
    INTO categorias (id_categoria, nombre_categoria, desc_categoria) VALUES (34, 'Grill', 'Parrillas eléctricas pequeñas')
    INTO categorias (id_categoria, nombre_categoria, desc_categoria) VALUES (35, 'Olla', 'Ollas eléctricas de cocción lenta')
    INTO categorias (id_categoria, nombre_categoria, desc_categoria) VALUES (36, 'Freidora', 'Freidoras de aire compactas')
    INTO categorias (id_categoria, nombre_categoria, desc_categoria) VALUES (37, 'Campana', 'Campanas extractoras portátiles')
    INTO categorias (id_categoria, nombre_categoria, desc_categoria) VALUES (38, 'Hervidor', 'Hervidores de agua eléctricos')
    INTO categorias (id_categoria, nombre_categoria, desc_categoria) VALUES (39, 'Repetidor', 'Repetidores Wi-Fi compactos')
    INTO categorias (id_categoria, nombre_categoria, desc_categoria) VALUES (40, 'Proyector', 'Proyectores portátiles multimedia')
    INTO categorias (id_categoria, nombre_categoria, desc_categoria) VALUES (41, 'Scanner', 'Escáneres portátiles de documentos')
    INTO categorias (id_categoria, nombre_categoria, desc_categoria) VALUES (42, 'Lupa', 'Lupas electrónicas recargables')
    INTO categorias (id_categoria, nombre_categoria, desc_categoria) VALUES (43, 'Grabador', 'Grabadores de voz compactos')
    INTO categorias (id_categoria, nombre_categoria, desc_categoria) VALUES (44, 'Medidor', 'Medidores láser para distancias')
    INTO categorias (id_categoria, nombre_categoria, desc_categoria) VALUES (45, 'Reloj', 'Relojes despertadores digitales')
    INTO categorias (id_categoria, nombre_categoria, desc_categoria) VALUES (46, 'Audifono', 'Audífonos inalámbricos pequeños')
    INTO categorias (id_categoria, nombre_categoria, desc_categoria) VALUES (47, 'Altavoz', 'Altavoces Bluetooth portátiles')
    INTO categorias (id_categoria, nombre_categoria, desc_categoria) VALUES (48, 'Control', 'Controles remotos universales')
    INTO categorias (id_categoria, nombre_categoria, desc_categoria) VALUES (49, 'Linterna', 'Linternas LED recargables')
    INTO categorias (id_categoria, nombre_categoria, desc_categoria) VALUES (50, 'Cargador', 'Cargadores rápidos y compactos')
SELECT 1 FROM DUAL; 
COMMIT;

INSERT ALL
    INTO productos (id_producto, nombre_producto, id_categoria) VALUES (1, 'TV LED 32"', 1)
    INTO productos (id_producto, nombre_producto, id_categoria) VALUES (2, 'TV Smart 40"', 1)
    INTO productos (id_producto, nombre_producto, id_categoria) VALUES (3, 'Monitor 24"', 1)
    INTO productos (id_producto, nombre_producto, id_categoria) VALUES (4, 'Proyector HD', 1)
    INTO productos (id_producto, nombre_producto, id_categoria) VALUES (5, 'Repetidor Wi-Fi', 1)*/

    INTO productos (id_producto, nombre_producto, id_categoria) VALUES (6, 'Microondas 20L', 2)
    INTO productos (id_producto, nombre_producto, id_categoria) VALUES (7, 'Horno Eléctrico', 2)
    INTO productos (id_producto, nombre_producto, id_categoria) VALUES (8, 'Freidora Aire', 2)
    INTO productos (id_producto, nombre_producto, id_categoria) VALUES (9, 'Olla Lenta', 2)
    INTO productos (id_producto, nombre_producto, id_categoria) VALUES (10, 'Tostador Doble', 2)

    INTO productos (id_producto, nombre_producto, id_categoria) VALUES (11, 'Licuadora 2 Vel.', 3)
    INTO productos (id_producto, nombre_producto, id_categoria) VALUES (12, 'Batidora Portátil', 3)
    INTO productos (id_producto, nombre_producto, id_categoria) VALUES (13, 'Procesador Alim.', 3)
    INTO productos (id_producto, nombre_producto, id_categoria) VALUES (14, 'Exprimidor Eléc.', 3)
    INTO productos (id_producto, nombre_producto, id_categoria) VALUES (15, 'Extractor Zumo', 3)

    INTO productos (id_producto, nombre_producto, id_categoria) VALUES (16, 'Ventilador Mesa', 4)
    INTO productos (id_producto, nombre_producto, id_categoria) VALUES (17, 'Purificador Aire', 4)
    INTO productos (id_producto, nombre_producto, id_categoria) VALUES (18, 'Calefactor Pers.', 4)
    INTO productos (id_producto, nombre_producto, id_categoria) VALUES (19, 'Enfriador Aire', 4)
    INTO productos (id_producto, nombre_producto, id_categoria) VALUES (20, 'Deshumidificador', 4)

    INTO productos (id_producto, nombre_producto, id_categoria) VALUES (21, 'Secador Cabello', 5)
    INTO productos (id_producto, nombre_producto, id_categoria) VALUES (22, 'Rizador Portátil', 5)
    INTO productos (id_producto, nombre_producto, id_categoria) VALUES (23, 'Cortapelo Rec.', 5)
    INTO productos (id_producto, nombre_producto, id_categoria) VALUES (24, 'Plancha Vapor', 5)
    INTO productos (id_producto, nombre_producto, id_categoria) VALUES (25, 'Plancha Vertical', 5)

    INTO productos (id_producto, nombre_producto, id_categoria) VALUES (26, 'Cafetera 2 Tazas', 6)
    INTO productos (id_producto, nombre_producto, id_categoria) VALUES (27, 'Molino Café', 6)
    INTO productos (id_producto, nombre_producto, id_categoria) VALUES (28, 'Hervidor Agua', 6)
    INTO productos (id_producto, nombre_producto, id_categoria) VALUES (29, 'Mezclador Mini', 6)
    INTO productos (id_producto, nombre_producto, id_categoria) VALUES (30, 'Termo Eléctrico', 6)*/
SELECT 1 FROM DUAL;
COMMIT;

